# Generated by Django 2.1 on 2019-05-14 15:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^01[0|1|2|5][0-9]{8}')])),
                ('profile_pic', models.ImageField(blank=True, default='profile_pics/nopic.jpeg', upload_to='profile_pics')),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
