# Generated by Django 2.1 on 2019-05-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='target',
            field=models.PositiveIntegerField(),
        ),
    ]
