# Generated by Django 2.1 on 2019-05-14 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20190514_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pimages',
            name='image',
            field=models.ImageField(null=True, upload_to='project_images/'),
        ),
    ]
